In [1]:
import cv2

In [2]:
img=cv2.imread('galaxy.jpg',0)   # 1 as is    # 0  blackwhite  -1 alpha channel transparency .color image is three dimensional matrix

In [3]:
print(type(img))

<class 'numpy.ndarray'>


In [4]:
print(img)

[[14 18 14 ... 20 15 16]
 [12 16 12 ... 20 15 17]
 [12 13 16 ... 14 24 21]
 ...
 [ 0  0  0 ...  5  8 14]
 [ 0  0  0 ...  2  3  9]
 [ 1  1  1 ...  1  1  3]]


In [5]:
print(img.shape)   #1485 height pixel, 99 width pixel screen small for image size if not resized

(1485, 990)


In [6]:
print(img.ndim)

2


In [7]:
cv2.imshow('Galaxy',img)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [8]:
resized_image=cv2.resize(img,(int(img.shape[1]*0.5),int(img.shape[0]*0.5)))  #by interpolating the index intensity  width: fx=first element. height: fy= second element
cv2.imshow('Galaxy',resized_image)   #img for original resize for resized 'Galaxy window name
cv2.imwrite('Galaxy_resized.jpg',resized_image)
cv2.waitKey(10000)   # 0any click remove the image  # put 2000 is 2000 mili second, 0 did not work that well
cv2.destroyAllWindows()  #close after 2000 ms

In [9]:
#######################
#other way

#import cv2
#import glob   # this file find paths names or certain pattern

#images=glob.glob("*.jpg")   list of images in directory in file path with jpg   , example ['C:\galaxy.jpg', ...]
#######################

list_image=['galaxy','kangaroos-rain-australia_71370_990x742','Lighthouse','Moon sinking, sun rising']

#print(list_image)
for item in list_image:
    
    #print(item)
    img_name=str(item)+'.jpg'
    print(img_name)
    img=cv2.imread(img_name,0)
    
    resized_image=cv2.resize(img,(100,100))  #by interpolating the index intensity  width: fx=first element. height: fy= second element

    img_new=str(item)+'_resized.jpg'
    cv2.imwrite(img_new,resized_image)    #or str(img_new)





galaxy.jpg
kangaroos-rain-australia_71370_990x742.jpg
Lighthouse.jpg
Moon sinking, sun rising.jpg


In [10]:
import cv2
import glob

images=glob.glob("*.jpg")

for image in images:
    print(image)
    img=cv2.imread(image,0)
    re=cv2.resize(img,(100,100))
    cv2.imshow("Hey",re)
    cv2.waitKey(5000)
    cv2.destroyAllWindows()
    cv2.imwrite("resized_"+image,re)

cat.jpg
cat2.jpg
cat4.jpg
galaxy.jpg
Galaxy_resized.jpg
kangaroos-rain-australia_71370_990x742.jpg
kangaroos-rain-australia_71370_990x742_resized.jpg
Lighthouse.jpg
Lighthouse_resized.jpg
Moon sinking, sun rising.jpg
Moon sinking, sun rising_resized.jpg
news.jpg
photo.jpg


In [15]:
import cv2

In [12]:
face_cascade=cv2.CascadeClassifier('haarcascade_frontalcatface_extended_download.xml')  

In [16]:
img=cv2.imread('cat4.jpg')

In [17]:
gray_image=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces=face_cascade.detectMultiScale(gray_image,scaleFactor=1.01,minNeighbors=10)

for x,y,w,h in faces:
    img=cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),3)
#print(type(faces))
#print(faces)



In [18]:
cv2.imwrite('Cat_detect.jpg',img)
cv2.imshow("Grey",img)
cv2.waitKey(10000)
cv2.destroyAllWindows()

In [161]:
import cv2,time

** Video **

In [163]:
import cv2,time
video=cv2.VideoCapture(0)
check, frame=video.read()     #this is the first frame
print(check)
print(frame)
time.sleep(3)

cv2.imshow('capture',frame)
cv2.waitKey(10000)
video.release()
cv2.destroyAllWindows()

True
[[[253 253 253]
  [253 253 253]
  [249 253 253]
  ...
  [151 146 162]
  [147 148 157]
  [147 148 157]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [147 147 158]
  [145 149 157]
  [146 150 158]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [146 150 158]
  [147 149 155]
  [148 150 156]]

 ...

 [[122 117 121]
  [121 116 120]
  [118 115 119]
  ...
  [ 69  69  69]
  [ 73  73  67]
  [ 74  74  68]]

 [[127 116 118]
  [126 115 117]
  [118 113 117]
  ...
  [ 68  68  68]
  [ 74  72  72]
  [ 74  72  72]]

 [[137 115 122]
  [139 117 124]
  [135 118 124]
  ...
  [ 65  65  65]
  [ 71  72  68]
  [ 72  73  69]]]


In [167]:
import cv2,time
video=cv2.VideoCapture(0)   # from camera 0   creating an object like a canvas figure, or video file path
a=1
while True:
    a=a+1
    check, frame=video.read()     #this is the first frame
    print(check)
    print(frame)
    #time.sleep(3)

    cv2.imshow('capture',frame)
    key=cv2.waitKey(1)             # lower number more snmoth
    if key==ord('q'):
        break
    
video.release()
cv2.destroyAllWindows()
print(a)

True
[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [153 151 169]
  [153 152 168]
  [151 150 166]]

 [[253 253 253]
  [253 253 253]
  [249 253 253]
  ...
  [150 149 165]
  [148 151 161]
  [148 151 161]]

 [[253 253 253]
  [253 253 253]
  [249 253 253]
  ...
  [150 153 170]
  [147 150 167]
  [149 152 169]]

 ...

 [[127 118 120]
  [126 117 119]
  [111 103 108]
  ...
  [101  97  98]
  [ 94  94  95]
  [ 95  95  96]]

 [[144 122 121]
  [146 124 123]
  [130 109 106]
  ...
  [100  99 103]
  [ 98  97 101]
  [ 98  97 101]]

 [[184 153 147]
  [191 160 154]
  [194 160 153]
  ...
  [ 97  95 101]
  [ 98  94 100]
  [ 97  93  99]]]
True
[[[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [151 152 169]
  [153 151 169]
  [151 149 167]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [151 150 166]
  [149 151 166]
  [149 151 166]]

 [[253 253 253]
  [253 253 253]
  [253 253 253]
  ...
  [149 150 167]
  [149 150 167]
  [149 150 167]]

 ...

 [[127 118 120]
  [127 118 120]
  [121 105

True
[[[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [143 148 158]
  [142 149 154]
  [143 150 155]]

 [[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [142 147 157]
  [143 149 157]
  [144 150 158]]

 [[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [143 149 157]
  [145 149 157]
  [146 150 158]]

 ...

 [[120 110 120]
  [117 107 117]
  [108  98 103]
  ...
  [ 89  88  92]
  [ 90  88  94]
  [ 90  88  94]]

 [[134 114 113]
  [132 112 111]
  [120 101  93]
  ...
  [ 91  91  92]
  [ 91  90  94]
  [ 94  93  97]]

 [[180 155 142]
  [184 159 146]
  [185 159 143]
  ...
  [ 90  90  91]
  [ 93  92  96]
  [ 94  93  97]]]
True
[[[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [148 152 160]
  [146 150 165]
  [147 151 166]]

 [[253 254 250]
  [253 254 250]
  [252 253 249]
  ...
  [148 152 160]
  [144 150 165]
  [143 149 164]]

 [[253 254 250]
  [253 254 250]
  [252 253 249]
  ...
  [146 150 158]
  [143 149 157]
  [143 149 157]]

 ...

 [[118 114 115]
  [116 112 113]
  [108  99

True
[[[253 253 253]
  [253 253 253]
  [251 251 252]
  ...
  [144 150 158]
  [145 150 155]
  [145 150 155]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [144 149 159]
  [143 148 158]
  [144 149 159]]

 [[253 253 253]
  [253 253 253]
  [248 253 249]
  ...
  [144 149 159]
  [143 148 158]
  [144 149 159]]

 ...

 [[117 110 112]
  [115 108 110]
  [107  99 104]
  ...
  [ 90  88  94]
  [ 85  89  90]
  [ 85  89  90]]

 [[141 120 117]
  [136 115 112]
  [127 108  98]
  ...
  [ 91  86  95]
  [ 85  88  92]
  [ 85  88  92]]

 [[186 154 142]
  [189 157 145]
  [185 158 138]
  ...
  [ 88  83  92]
  [ 87  87  87]
  [ 88  88  88]]]
True
[[[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [136 150 163]
  [147 146 162]
  [146 145 161]]

 [[253 254 250]
  [252 253 249]
  [250 251 247]
  ...
  [136 151 159]
  [146 149 159]
  [145 148 158]]

 [[253 254 250]
  [253 254 250]
  [251 252 248]
  ...
  [136 151 159]
  [144 149 159]
  [144 149 159]]

 ...

 [[128 112 114]
  [125 109 111]
  [110  98

True
[[[253 253 253]
  [252 252 252]
  [250 249 253]
  ...
  [145 148 158]
  [146 149 153]
  [146 149 153]]

 [[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [146 149 159]
  [147 148 157]
  [147 148 157]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [145 148 158]
  [147 147 158]
  [147 147 158]]

 ...

 [[128 112 115]
  [126 110 113]
  [119 100 104]
  ...
  [ 91  89  90]
  [ 95  88  89]
  [ 95  88  89]]

 [[156 126 122]
  [152 122 118]
  [144 113 107]
  ...
  [ 88  86  92]
  [ 93  88  92]
  [ 93  88  92]]

 [[186 156 139]
  [194 164 147]
  [200 167 152]
  ...
  [ 89  86  95]
  [ 91  86  95]
  [ 91  86  95]]]
True
[[[253 253 253]
  [253 253 253]
  [250 250 250]
  ...
  [147 153 156]
  [145 152 157]
  [146 153 158]]

 [[253 254 250]
  [253 254 250]
  [251 251 251]
  ...
  [145 153 156]
  [143 151 159]
  [144 152 160]]

 [[253 254 250]
  [253 254 250]
  [251 251 251]
  ...
  [144 150 158]
  [144 150 158]
  [144 150 158]]

 ...

 [[123 116 118]
  [121 114 116]
  [101  97

True
[[[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [146 149 159]
  [147 152 157]
  [146 151 156]]

 [[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [145 150 155]
  [143 151 154]
  [144 152 155]]

 [[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [145 151 154]
  [151 150 154]
  [152 151 155]]

 ...

 [[135 114 117]
  [130 109 112]
  [115  96  93]
  ...
  [ 88  89  85]
  [ 92  94  83]
  [ 92  94  83]]

 [[158 128 124]
  [157 127 123]
  [149 120 114]
  ...
  [ 82  87  83]
  [ 91  94  85]
  [ 93  96  87]]

 [[187 156 141]
  [190 159 144]
  [198 169 156]
  ...
  [ 82  90  85]
  [ 87  93  87]
  [ 89  95  89]]]
True
[[[253 254 250]
  [252 253 249]
  [249 250 246]
  ...
  [144 150 158]
  [146 152 155]
  [146 152 155]]

 [[253 254 250]
  [252 253 249]
  [249 250 246]
  ...
  [143 150 155]
  [145 151 154]
  [145 151 154]]

 [[253 254 250]
  [253 254 250]
  [251 251 251]
  ...
  [142 149 154]
  [144 151 151]
  [144 151 151]]

 ...

 [[128 119 126]
  [125 116 123]
  [115 104

True
[[[253 253 253]
  [252 252 252]
  [247 247 247]
  ...
  [144 148 163]
  [143 148 158]
  [143 148 158]]

 [[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [144 148 156]
  [144 148 156]
  [144 148 156]]

 [[253 254 250]
  [253 254 250]
  [247 251 251]
  ...
  [145 149 157]
  [146 150 158]
  [145 149 157]]

 ...

 [[127 118 119]
  [122 113 114]
  [117 101 103]
  ...
  [ 90  88  94]
  [ 92  87  96]
  [ 92  87  96]]

 [[151 129 122]
  [145 123 116]
  [140 111 105]
  ...
  [ 89  87  93]
  [ 91  87  93]
  [ 92  88  94]]

 [[190 159 151]
  [198 167 159]
  [199 167 155]
  ...
  [ 88  88  89]
  [ 88  85  89]
  [ 89  86  90]]]
True
[[[253 253 253]
  [253 253 253]
  [252 253 249]
  ...
  [151 149 155]
  [146 150 158]
  [146 150 158]]

 [[253 253 253]
  [253 253 253]
  [251 252 248]
  ...
  [147 149 155]
  [146 150 158]
  [146 150 158]]

 [[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [151 150 154]
  [145 149 157]
  [145 149 157]]

 ...

 [[121 117 118]
  [119 115 116]
  [111 102

True
[[[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [145 147 162]
  [147 147 158]
  [144 144 155]]

 [[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [144 147 157]
  [146 147 156]
  [144 145 154]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [145 148 158]
  [146 147 156]
  [146 147 156]]

 ...

 [[129 120 122]
  [125 116 118]
  [114  98 100]
  ...
  [ 81  90  90]
  [ 85  88  92]
  [ 86  89  93]]

 [[151 129 128]
  [142 120 119]
  [136 109 103]
  ...
  [ 82  84  90]
  [ 83  84  93]
  [ 84  85  94]]

 [[186 157 151]
  [192 163 157]
  [194 165 157]
  ...
  [ 77  78  87]
  [ 85  80  89]
  [ 86  81  90]]]
True
[[[253 253 253]
  [253 253 253]
  [247 251 251]
  ...
  [148 150 156]
  [148 149 158]
  [148 149 158]]

 [[253 254 250]
  [253 254 250]
  [251 251 251]
  ...
  [146 148 163]
  [148 148 159]
  [148 148 159]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [146 148 163]
  [148 148 159]
  [148 148 159]]

 ...

 [[121 121 108]
  [120 120 107]
  [111 107

True
[[[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [143 151 159]
  [147 150 154]
  [146 149 153]]

 [[253 254 250]
  [252 253 249]
  [250 250 250]
  ...
  [142 149 154]
  [144 151 151]
  [144 151 151]]

 [[253 254 250]
  [253 254 250]
  [247 251 251]
  ...
  [143 149 157]
  [145 150 155]
  [145 150 155]]

 ...

 [[125 116 117]
  [122 113 114]
  [119 103 105]
  ...
  [ 92  88  89]
  [ 89  89  89]
  [ 88  88  88]]

 [[146 121 121]
  [144 119 119]
  [144 117 111]
  ...
  [ 86  90  91]
  [ 84  88  88]
  [ 84  88  88]]

 [[187 155 151]
  [188 156 152]
  [195 167 151]
  ...
  [ 83  90  89]
  [ 81  88  87]
  [ 81  88  87]]]
True
[[[253 253 253]
  [252 252 252]
  [247 251 251]
  ...
  [145 148 158]
  [146 148 163]
  [146 148 163]]

 [[253 253 253]
  [253 253 253]
  [247 251 251]
  ...
  [145 148 158]
  [145 146 163]
  [146 147 164]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [144 145 154]
  [146 144 162]
  [146 144 162]]

 ...

 [[130 114 116]
  [128 112 114]
  [118 102

True
[[[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [145 151 159]
  [143 151 159]
  [143 151 159]]

 [[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [145 149 157]
  [148 150 156]
  [148 150 156]]

 [[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [146 147 156]
  [148 150 156]
  [148 150 156]]

 ...

 [[125 117 114]
  [122 114 111]
  [118 107 108]
  ...
  [ 85  87  93]
  [ 85  89  89]
  [ 85  89  89]]

 [[136 127 108]
  [137 128 109]
  [131 116  96]
  ...
  [ 89  88  92]
  [ 89  89  90]
  [ 89  89  90]]

 [[179 165 140]
  [181 167 142]
  [188 166 143]
  ...
  [ 89  88  92]
  [ 89  86  90]
  [ 88  85  89]]]
True
[[[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [149 151 157]
  [145 151 159]
  [144 150 158]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [145 150 155]
  [142 147 157]
  [142 147 157]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [145 150 155]
  [145 149 157]
  [145 149 157]]

 ...

 [[131 118 130]
  [126 113 125]
  [111 102

True
[[[253 253 253]
  [252 252 252]
  [250 250 250]
  ...
  [148 146 164]
  [146 149 159]
  [145 148 158]]

 [[253 253 253]
  [252 252 252]
  [250 250 250]
  ...
  [147 148 165]
  [143 147 162]
  [142 146 161]]

 [[253 253 253]
  [252 252 252]
  [250 250 250]
  ...
  [147 146 162]
  [147 145 163]
  [147 145 163]]

 ...

 [[125 122 118]
  [122 119 115]
  [113 104  99]
  ...
  [ 89  89  89]
  [ 87  89  83]
  [ 89  91  85]]

 [[153 136 126]
  [153 136 126]
  [151 122 114]
  ...
  [ 84  88  88]
  [ 82  89  88]
  [ 83  90  89]]

 [[182 156 140]
  [187 161 145]
  [199 167 155]
  ...
  [ 81  88  87]
  [ 81  90  89]
  [ 82  91  90]]]
True
[[[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [146 151 156]
  [143 152 157]
  [143 152 157]]

 [[253 254 250]
  [252 253 249]
  [250 250 250]
  ...
  [145 148 158]
  [144 149 159]
  [145 150 160]]

 [[253 254 250]
  [253 254 250]
  [251 251 251]
  ...
  [143 149 157]
  [146 149 159]
  [146 149 159]]

 ...

 [[122 119 115]
  [119 116 112]
  [119 103

True
[[[253 253 253]
  [252 252 252]
  [250 250 250]
  ...
  [146 148 163]
  [144 149 159]
  [143 148 158]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [143 149 164]
  [143 150 160]
  [143 150 160]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [143 149 164]
  [144 149 159]
  [145 150 160]]

 ...

 [[120 113 114]
  [120 113 114]
  [111 100 102]
  ...
  [ 93  93  94]
  [ 90  89  93]
  [ 91  90  94]]

 [[144 125 128]
  [142 123 126]
  [136 111 111]
  ...
  [ 91  91  92]
  [ 90  88  94]
  [ 91  89  95]]

 [[176 154 147]
  [183 161 154]
  [194 164 160]
  ...
  [ 85  89  89]
  [ 84  89  94]
  [ 85  90  95]]]
True
[[[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [150 145 161]
  [142 147 157]
  [143 148 158]]

 [[253 253 253]
  [253 253 253]
  [250 250 250]
  ...
  [144 145 162]
  [143 147 162]
  [143 147 162]]

 [[253 254 250]
  [253 254 250]
  [250 250 250]
  ...
  [145 147 162]
  [145 148 158]
  [145 148 158]]

 ...

 [[125 115 112]
  [126 116 113]
  [115 104

True
[[[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [146 149 159]
  [145 151 154]
  [145 151 154]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [145 148 158]
  [144 149 154]
  [144 149 154]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [144 148 156]
  [144 148 156]
  [142 146 154]]

 ...

 [[125 114 115]
  [124 113 114]
  [110 103 104]
  ...
  [ 89  89  89]
  [ 90  90  91]
  [ 91  91  92]]

 [[139 120 117]
  [139 120 117]
  [129 112  97]
  ...
  [ 94  94  94]
  [ 91  87  98]
  [ 91  87  98]]

 [[180 156 140]
  [185 161 145]
  [188 163 145]
  ...
  [ 93  93  93]
  [ 92  86  97]
  [ 91  85  96]]]
True
[[[253 253 253]
  [253 253 253]
  [250 249 253]
  ...
  [151 146 162]
  [147 146 162]
  [148 147 163]]

 [[253 253 253]
  [253 253 253]
  [251 251 252]
  ...
  [148 143 159]
  [144 147 157]
  [144 147 157]]

 [[253 253 253]
  [252 252 252]
  [250 250 250]
  ...
  [144 146 161]
  [142 147 157]
  [140 145 155]]

 ...

 [[125 114 115]
  [125 114 115]
  [110  99

True
[[[253 253 253]
  [253 253 253]
  [250 251 247]
  ...
  [147 145 151]
  [146 145 149]
  [146 145 149]]

 [[253 253 253]
  [253 253 253]
  [250 250 250]
  ...
  [146 145 149]
  [143 146 150]
  [142 145 149]]

 [[253 253 253]
  [252 252 252]
  [250 250 250]
  ...
  [142 146 147]
  [140 147 147]
  [140 147 147]]

 ...

 [[116 113 117]
  [116 113 117]
  [103 101 101]
  ...
  [ 94  96  90]
  [ 89  92  83]
  [ 88  91  82]]

 [[120 112 117]
  [120 112 117]
  [115  99 101]
  ...
  [ 89  92  83]
  [ 88  91  82]
  [ 88  91  82]]

 [[143 126 118]
  [143 126 118]
  [144 125 108]
  ...
  [ 83  85  79]
  [ 88  89  85]
  [ 89  90  86]]]
True
[[[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [140 146 154]
  [142 148 156]
  [142 148 156]]

 [[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [142 148 156]
  [140 149 154]
  [138 147 152]]

 [[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [140 148 156]
  [138 146 154]
  [138 146 154]]

 ...

 [[118 112 118]
  [118 112 118]
  [110 102

True
[[[253 253 253]
  [252 252 252]
  [250 250 250]
  ...
  [141 143 158]
  [143 145 151]
  [143 145 151]]

 [[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [146 144 150]
  [142 144 150]
  [143 145 151]]

 [[253 253 253]
  [252 252 252]
  [250 251 247]
  ...
  [147 146 150]
  [143 145 151]
  [143 145 151]]

 ...

 [[119 107 112]
  [118 106 111]
  [110  99 101]
  ...
  [ 88  90  84]
  [ 87  89  83]
  [ 88  90  84]]

 [[134 114 108]
  [137 117 111]
  [131 109 102]
  ...
  [ 88  90  84]
  [ 89  93  80]
  [ 88  92  79]]

 [[176 153 135]
  [179 156 138]
  [183 157 134]
  ...
  [ 84  86  80]
  [ 88  92  79]
  [ 88  92  79]]]
True
[[[253 253 253]
  [252 252 252]
  [246 244 244]
  ...
  [141 142 159]
  [141 143 158]
  [141 143 158]]

 [[253 253 253]
  [252 252 252]
  [247 247 247]
  ...
  [142 146 161]
  [142 146 161]
  [142 146 161]]

 [[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [142 145 155]
  [140 144 159]
  [140 144 159]]

 ...

 [[121 110 111]
  [120 109 110]
  [118 102

True
[[[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [141 144 154]
  [142 143 160]
  [142 143 160]]

 [[253 253 253]
  [252 252 252]
  [247 247 247]
  ...
  [138 147 152]
  [142 146 154]
  [141 145 153]]

 [[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [142 147 152]
  [142 147 152]
  [141 146 151]]

 ...

 [[116 107 109]
  [116 107 109]
  [107  96  97]
  ...
  [ 89  89  89]
  [ 84  88  88]
  [ 85  89  89]]

 [[124 107 104]
  [121 104 101]
  [118  98  92]
  ...
  [ 88  86  87]
  [ 89  89  89]
  [ 89  89  89]]

 [[166 145 142]
  [166 145 142]
  [168 143 130]
  ...
  [ 84  82  82]
  [ 88  88  88]
  [ 89  89  89]]]
True
[[[253 253 253]
  [253 253 253]
  [252 252 252]
  ...
  [140 146 154]
  [147 147 148]
  [147 147 148]]

 [[253 253 253]
  [252 252 252]
  [247 251 251]
  ...
  [141 145 153]
  [143 145 151]
  [143 145 151]]

 [[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [141 144 154]
  [142 146 154]
  [141 145 153]]

 ...

 [[111 113 107]
  [110 112 106]
  [ 99  97

True
[[[253 253 253]
  [252 252 252]
  [251 251 251]
  ...
  [144 148 149]
  [139 144 154]
  [139 144 154]]

 [[253 253 253]
  [252 252 252]
  [250 250 250]
  ...
  [147 145 151]
  [141 144 154]
  [140 143 153]]

 [[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [147 144 153]
  [143 143 154]
  [143 143 154]]

 ...

 [[117 107 112]
  [116 106 111]
  [105  96  98]
  ...
  [ 86  86  86]
  [ 83  87  87]
  [ 83  87  87]]

 [[123 108 106]
  [123 108 106]
  [116  96  95]
  ...
  [ 86  86  86]
  [ 86  86  80]
  [ 86  86  80]]

 [[157 139 133]
  [156 138 132]
  [153 130 125]
  ...
  [ 84  84  84]
  [ 90  88  82]
  [ 88  86  80]]]
True
[[[253 253 253]
  [252 252 252]
  [247 245 245]
  ...
  [140 144 152]
  [142 144 150]
  [142 144 150]]

 [[253 253 253]
  [252 252 252]
  [247 247 247]
  ...
  [140 144 152]
  [142 145 149]
  [143 146 150]]

 [[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [146 144 150]
  [140 145 150]
  [140 145 150]]

 ...

 [[115 111 111]
  [113 109 109]
  [109  94

True
[[[253 254 250]
  [252 253 249]
  [250 251 247]
  ...
  [142 146 154]
  [140 146 154]
  [140 146 154]]

 [[253 254 250]
  [252 253 249]
  [247 248 244]
  ...
  [140 143 153]
  [141 145 153]
  [141 145 153]]

 [[253 254 250]
  [252 253 249]
  [250 250 251]
  ...
  [142 141 157]
  [146 141 157]
  [146 141 157]]

 ...

 [[116 109 110]
  [113 106 107]
  [108  98  95]
  ...
  [ 90  90  90]
  [ 87  87  87]
  [ 84  84  84]]

 [[137 118 110]
  [132 113 105]
  [125 105  91]
  ...
  [ 89  89  90]
  [ 87  87  88]
  [ 86  86  87]]

 [[182 151 143]
  [185 154 146]
  [187 161 145]
  ...
  [ 81  81  82]
  [ 78  82  83]
  [ 78  82  83]]]
True
[[[253 255 249]
  [253 255 249]
  [249 249 243]
  ...
  [140 144 152]
  [140 146 149]
  [140 146 149]]

 [[253 255 249]
  [252 254 248]
  [245 247 241]
  ...
  [138 144 152]
  [142 144 150]
  [142 144 150]]

 [[253 254 250]
  [253 254 250]
  [249 249 249]
  ...
  [142 143 152]
  [142 143 152]
  [142 143 152]]

 ...

 [[121 118 108]
  [115 112 102]
  [115 102

True
[[[253 254 250]
  [252 253 249]
  [249 250 246]
  ...
  [146 143 152]
  [146 142 153]
  [146 142 153]]

 [[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [147 144 153]
  [147 143 154]
  [147 143 154]]

 [[253 253 253]
  [253 253 253]
  [249 249 249]
  ...
  [147 144 153]
  [146 142 153]
  [145 141 152]]

 ...

 [[122 115 110]
  [120 113 108]
  [106 103  99]
  ...
  [ 94  93  84]
  [ 90  88  88]
  [ 91  89  89]]

 [[133 115 109]
  [134 116 110]
  [119 103  97]
  ...
  [ 94  94  83]
  [ 88  89  85]
  [ 89  90  86]]

 [[167 147 133]
  [174 154 140]
  [176 149 141]
  ...
  [ 89  90  81]
  [ 80  85  81]
  [ 79  84  80]]]
True
[[[253 254 250]
  [252 253 249]
  [249 246 242]
  ...
  [143 143 154]
  [146 143 152]
  [146 143 152]]

 [[253 254 250]
  [252 253 249]
  [245 246 242]
  ...
  [143 145 151]
  [146 144 150]
  [146 144 150]]

 [[253 254 250]
  [252 253 249]
  [247 247 247]
  ...
  [143 145 151]
  [142 142 153]
  [142 142 153]]

 ...

 [[126 105 114]
  [125 104 113]
  [104  93

True
[[[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [140 144 152]
  [142 142 153]
  [142 142 153]]

 [[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [141 144 154]
  [140 143 153]
  [140 143 153]]

 [[253 253 253]
  [253 253 253]
  [248 252 252]
  ...
  [141 144 154]
  [140 145 155]
  [139 144 154]]

 ...

 [[116 108 126]
  [116 108 126]
  [102  97 113]
  ...
  [ 89  89  89]
  [ 82  91  91]
  [ 82  91  91]]

 [[126 103 117]
  [125 102 116]
  [109  98 105]
  ...
  [ 87  91  91]
  [ 85  94  93]
  [ 83  92  91]]

 [[147 121 125]
  [146 120 124]
  [149 120 119]
  ...
  [ 84  88  88]
  [ 81  92  92]
  [ 81  92  92]]]
True
[[[253 253 253]
  [253 253 253]
  [252 252 253]
  ...
  [140 144 159]
  [143 145 151]
  [144 146 152]]

 [[253 253 253]
  [253 253 253]
  [250 250 251]
  ...
  [140 144 159]
  [144 145 154]
  [144 145 154]]

 [[253 253 253]
  [253 253 253]
  [250 250 251]
  ...
  [141 144 154]
  [143 144 153]
  [142 143 152]]

 ...

 [[111 108 117]
  [109 106 115]
  [ 91  87

True
[[[253 253 253]
  [252 252 252]
  [249 249 249]
  ...
  [141 145 153]
  [140 143 153]
  [140 143 153]]

 [[253 253 253]
  [253 253 253]
  [246 250 250]
  ...
  [140 145 155]
  [139 145 153]
  [139 145 153]]

 [[253 253 253]
  [253 253 253]
  [246 253 252]
  ...
  [138 145 155]
  [140 146 154]
  [140 146 154]]

 ...

 [[111 108 104]
  [111 108 104]
  [101  97  97]
  ...
  [ 88  88  88]
  [ 89  89  89]
  [ 88  88  88]]

 [[125 112 105]
  [119 106  99]
  [114 101  94]
  ...
  [ 86  90  90]
  [ 89  88  92]
  [ 89  88  92]]

 [[150 135 120]
  [149 134 119]
  [150 131 114]
  ...
  [ 83  89  92]
  [ 83  88  93]
  [ 83  88  93]]]
True
[[[253 253 253]
  [253 253 253]
  [247 247 247]
  ...
  [130 143 158]
  [134 143 157]
  [132 141 155]]

 [[253 253 253]
  [252 252 252]
  [246 246 246]
  ...
  [134 143 157]
  [136 143 153]
  [136 143 153]]

 [[253 253 253]
  [253 253 253]
  [247 251 251]
  ...
  [138 145 155]
  [137 144 154]
  [137 144 154]]

 ...

 [[118 111 112]
  [118 111 112]
  [103  96

True
[[[253 253 253]
  [253 253 253]
  [247 251 251]
  ...
  [141 143 158]
  [144 144 155]
  [143 143 154]]

 [[253 253 253]
  [253 253 253]
  [245 252 251]
  ...
  [139 143 158]
  [141 144 154]
  [141 144 154]]

 [[253 253 253]
  [253 253 253]
  [244 251 250]
  ...
  [137 143 158]
  [142 146 154]
  [142 146 154]]

 ...

 [[119 108 115]
  [117 106 113]
  [102  93 100]
  ...
  [ 88  85  94]
  [ 86  84  90]
  [ 87  85  91]]

 [[129 113 116]
  [128 112 115]
  [112  93  96]
  ...
  [ 91  88  92]
  [ 88  85  89]
  [ 89  86  90]]

 [[152 136 118]
  [157 141 123]
  [160 138 129]
  ...
  [ 93  89  90]
  [ 88  85  81]
  [ 87  84  80]]]
True
[[[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [142 147 157]
  [138 147 152]
  [137 146 151]]

 [[253 253 253]
  [252 252 252]
  [245 249 250]
  ...
  [138 146 154]
  [140 147 152]
  [139 146 151]]

 [[253 253 253]
  [252 252 252]
  [249 249 250]
  ...
  [137 146 151]
  [139 147 150]
  [138 146 149]]

 ...

 [[111 108 117]
  [108 105 114]
  [ 97  97

True
[[[253 253 253]
  [253 253 253]
  [249 249 249]
  ...
  [144 145 154]
  [144 145 154]
  [143 144 153]]

 [[253 253 253]
  [253 253 253]
  [249 249 249]
  ...
  [143 144 153]
  [143 144 153]
  [142 143 152]]

 [[253 253 253]
  [253 253 253]
  [247 251 251]
  ...
  [141 145 153]
  [143 143 154]
  [143 143 154]]

 ...

 [[114 112 118]
  [112 110 116]
  [ 97  97  98]
  ...
  [ 92  91  87]
  [ 89  90  86]
  [ 89  90  86]]

 [[119 110 112]
  [119 110 112]
  [109 100 102]
  ...
  [ 91  89  89]
  [ 91  89  89]
  [ 91  89  89]]

 [[153 130 133]
  [151 128 131]
  [155 130 130]
  ...
  [ 85  83  83]
  [ 89  87  88]
  [ 91  89  90]]]
True
[[[253 253 253]
  [253 253 253]
  [251 251 251]
  ...
  [143 142 158]
  [142 142 153]
  [142 142 153]]

 [[253 253 253]
  [253 253 253]
  [246 253 252]
  ...
  [143 143 154]
  [143 142 158]
  [142 141 157]]

 [[253 254 250]
  [253 254 250]
  [246 253 252]
  ...
  [143 143 154]
  [142 142 153]
  [142 142 153]]

 ...

 [[112 110 110]
  [112 110 110]
  [102 102

True
[[[253 253 253]
  [253 253 253]
  [247 251 251]
  ...
  [137 142 159]
  [143 142 158]
  [143 142 158]]

 [[253 253 253]
  [253 253 253]
  [243 250 249]
  ...
  [139 143 158]
  [140 143 153]
  [140 143 153]]

 [[249 253 253]
  [248 252 252]
  [243 250 249]
  ...
  [139 144 154]
  [141 145 153]
  [140 144 152]]

 ...

 [[111 111 112]
  [110 110 111]
  [106 102 102]
  ...
  [ 89  89  90]
  [ 90  90  91]
  [ 89  89  90]]

 [[129 114 112]
  [128 113 111]
  [122 104  98]
  ...
  [ 91  89  89]
  [ 86  86  86]
  [ 88  88  88]]

 [[161 139 130]
  [164 142 133]
  [171 142 134]
  ...
  [ 84  84  84]
  [ 86  86  86]
  [ 88  88  88]]]
True
[[[253 253 253]
  [253 253 253]
  [247 251 251]
  ...
  [139 147 150]
  [142 143 152]
  [142 143 152]]

 [[253 253 253]
  [253 253 253]
  [249 249 249]
  ...
  [138 147 147]
  [143 145 151]
  [143 145 151]]

 [[253 253 253]
  [253 253 253]
  [247 247 247]
  ...
  [140 147 147]
  [140 145 150]
  [140 145 150]]

 ...

 [[111 109 110]
  [110 108 109]
  [104 100